In [2]:
import pandas as pd
import numpy  as np
from numpy import nan as NA

In [3]:
%config Completer.use_jedi = False

In [4]:
string_data = pd.Series(['aardvark','artichoke',np.nan,'avocado'])
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [5]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [6]:
data = pd.Series([1, NA, 3.5, NA, 7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [7]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA], 
                   [NA, NA, NA], [NA, 6.5, 3.]])

cleaned = data.dropna(how='all', axis=1)
print("data")
data

data


0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [8]:
print("cleaned")
cleaned

cleaned


0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [9]:
df = pd.DataFrame(np.random.randn(7, 3))
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA
df

0         1         2
0 -1.000019       NaN       NaN
1 -0.327799       NaN       NaN
2 -1.800374       NaN -0.157312
3 -1.136498       NaN  1.192138
4 -1.492993 -0.284657  0.700824
5  0.128589 -0.016037 -1.123264
6  1.564909  0.637375  1.244495

In [10]:
df.dropna()

0         1         2
4 -1.492993 -0.284657  0.700824
5  0.128589 -0.016037 -1.123264
6  1.564909  0.637375  1.244495

In [11]:
df.dropna(thresh=2)

0         1         2
2 -1.800374       NaN -0.157312
3 -1.136498       NaN  1.192138
4 -1.492993 -0.284657  0.700824
5  0.128589 -0.016037 -1.123264
6  1.564909  0.637375  1.244495

In [12]:
df.fillna(0)

0         1         2
0 -1.000019  0.000000  0.000000
1 -0.327799  0.000000  0.000000
2 -1.800374  0.000000 -0.157312
3 -1.136498  0.000000  1.192138
4 -1.492993 -0.284657  0.700824
5  0.128589 -0.016037 -1.123264
6  1.564909  0.637375  1.244495

In [13]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0 -1.000019  0.500000  0.000000
1 -0.327799  0.500000  0.000000
2 -1.800374  0.500000 -0.157312
3 -1.136498  0.500000  1.192138
4 -1.492993 -0.284657  0.700824
5  0.128589 -0.016037 -1.123264
6  1.564909  0.637375  1.244495

In [14]:
_ = df.fillna(0, inplace=True)
df

0         1         2
0 -1.000019  0.000000  0.000000
1 -0.327799  0.000000  0.000000
2 -1.800374  0.000000 -0.157312
3 -1.136498  0.000000  1.192138
4 -1.492993 -0.284657  0.700824
5  0.128589 -0.016037 -1.123264
6  1.564909  0.637375  1.244495

In [15]:
df = pd.DataFrame(np.random.randn(6, 3))
df.iloc[2:, 1] = NA
df.iloc[4:, 2] = NA
df

0         1         2
0  0.531059 -0.881891 -0.481643
1  0.282216  0.409153  1.051738
2  0.779650       NaN -0.591246
3 -0.238101       NaN -0.041888
4 -0.299708       NaN       NaN
5 -0.876068       NaN       NaN

In [16]:
df.fillna(method='ffill')

0         1         2
0  0.531059 -0.881891 -0.481643
1  0.282216  0.409153  1.051738
2  0.779650  0.409153 -0.591246
3 -0.238101  0.409153 -0.041888
4 -0.299708  0.409153 -0.041888
5 -0.876068  0.409153 -0.041888

In [17]:
df.fillna(method='ffill', limit=2)

0         1         2
0  0.531059 -0.881891 -0.481643
1  0.282216  0.409153  1.051738
2  0.779650  0.409153 -0.591246
3 -0.238101  0.409153 -0.041888
4 -0.299708       NaN -0.041888
5 -0.876068       NaN -0.041888

In [18]:
data = pd.Series([1., NA, 3.5, NA, 7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [19]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                     'k2': [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [20]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [21]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [22]:
data['v1'] = range(7)
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [23]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [24]:
 data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
                               'Pastarami', 'corned beef', 'Bacon',
                                'pastarami','honey ham', 'nova lox'],
                     'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3    Pastarami     6.0
4  corned beef     7.5
5        Bacon     8.0
6    pastarami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [25]:
meat_to_animal = {
    'bacon': 'pig',
    'pulled pork': 'pig',
    'pastarami': 'cow',
    'corned beef': 'cow',
    'honey ham': 'pig',
    'nova lox': 'salmon'
}

In [26]:
lowercased = data['food'].str.lower()
lowercased

0          bacon
1    pulled pork
2          bacon
3      pastarami
4    corned beef
5          bacon
6      pastarami
7      honey ham
8       nova lox
Name: food, dtype: object

In [27]:
data['animal'] = lowercased.map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3    Pastarami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6    pastarami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [28]:
data['food'].map(lambda x: meat_to_animal[x.lower()])
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3    Pastarami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6    pastarami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [29]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [30]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [31]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [32]:
data.replace([-999, -1000],[np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [33]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [34]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                   index=['Ohio', 'Colorado', 'New York'],
                   columns=['one', 'two', 'three', 'four'])


In [35]:
transform = lambda x: x[:4].upper()
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [37]:
data.index = data.index.map(transform)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [39]:
data.rename(index=str.title, columns=str.upper) 


ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [40]:
data.rename(index={'OHIO': 'INDIANA'}, 
            columns={'three':'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [42]:
data.rename(index={'OHIO': 'INDIANA'}, inplace=True) 
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

In [44]:
ages = [20, 22, 25, 27, 21, 23, 31, 61, 45, 41, 32]

In [45]:
bins = [18, 25, 35, 60, 100]
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 11
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [46]:
cats.codes

array([0, 0, 0, 1, 0, 0, 1, 3, 2, 2, 1], dtype=int8)

In [47]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [49]:
pd.value_counts(cats)

(18, 25]     5
(25, 35]     3
(35, 60]     2
(60, 100]    1
dtype: int64

In [50]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 11
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [51]:
group_names = ['Youth','YoungAdult', 'MiddleAged', 'Senior']
pd.cut(ages, bins, labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 11
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [53]:
data = np.random.rand(20)
pd.cut(data, 4,precision=2)

[(0.51, 0.75], (0.043, 0.28], (0.75, 0.98], (0.043, 0.28], (0.28, 0.51], ..., (0.51, 0.75], (0.28, 0.51], (0.75, 0.98], (0.28, 0.51], (0.28, 0.51]]
Length: 20
Categories (4, interval[float64]): [(0.043, 0.28] < (0.28, 0.51] < (0.51, 0.75] < (0.75, 0.98]]

In [54]:
data = np.random.rand(1000)
cats = pd.qcut(data, 4)
cats

[(0.233, 0.492], (0.492, 0.728], (-0.000637, 0.233], (0.492, 0.728], (-0.000637, 0.233], ..., (-0.000637, 0.233], (-0.000637, 0.233], (0.728, 0.998], (-0.000637, 0.233], (0.728, 0.998]]
Length: 1000
Categories (4, interval[float64]): [(-0.000637, 0.233] < (0.233, 0.492] < (0.492, 0.728] < (0.728, 0.998]]

In [55]:
pd.value_counts(cats)

(0.728, 0.998]        250
(0.492, 0.728]        250
(0.233, 0.492]        250
(-0.000637, 0.233]    250
dtype: int64

In [56]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

[(0.0884, 0.492], (0.492, 0.897], (0.0884, 0.492], (0.492, 0.897], (0.0884, 0.492], ..., (-0.000637, 0.0884], (-0.000637, 0.0884], (0.897, 0.998], (-0.000637, 0.0884], (0.492, 0.897]]
Length: 1000
Categories (4, interval[float64]): [(-0.000637, 0.0884] < (0.0884, 0.492] < (0.492, 0.897] < (0.897, 0.998]]

In [57]:
data = pd.DataFrame(np.random.randn(1000, 4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.015350     0.002237     0.040564    -0.019621
std       1.040510     1.060235     1.022952     1.003220
min      -3.742302    -4.193370    -3.588736    -2.928297
25%      -0.729924    -0.722356    -0.625445    -0.733913
50%       0.048296     0.003131     0.030198    -0.064105
75%       0.747934     0.680779     0.729479     0.663627
max       3.132262     3.530696     3.574367     2.900802

In [58]:
col = data[2]
col[np.abs(col)>3]

23    -3.186976
684   -3.588736
885    3.574367
Name: 2, dtype: float64

In [59]:
data[(np.abs(data) > 3).any(1)]

0         1         2         3
23  -0.637438  2.344978 -3.186976  0.568587
110 -3.101190 -0.260458  1.559665 -1.554508
141  0.248279 -4.193370  1.393655 -0.263415
156 -3.016589 -0.170552  0.640997 -0.694991
194 -0.348425  3.530696 -0.477525 -1.037146
350  1.561729  3.150589 -2.031054 -0.887159
406 -3.742302  2.119638  0.486920  0.243203
647 -3.649890  1.363982  1.687596 -0.137961
684  0.850625  0.885951 -3.588736 -0.706692
722  3.132262 -1.044047  1.111065  0.725768
871 -3.031423  1.311083 -1.071847 -0.546047
885 -0.551413  0.632698  3.574367  0.539266
933 -3.263433 -0.813873 -0.182793 -0.477609
990  0.185197  3.024645 -0.435100 -1.462656

In [62]:
data[np.abs(data) > 3] = np.sign(data) * 3
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.017022     0.002725     0.040766    -0.019621
std       1.034360     1.054020     1.018623     1.003220
min      -3.000000    -3.000000    -3.000000    -2.928297
25%      -0.729924    -0.722356    -0.625445    -0.733913
50%       0.048296     0.003131     0.030198    -0.064105
75%       0.747934     0.680779     0.729479     0.663627
max       3.000000     3.000000     3.000000     2.900802

In [63]:
np.sign(data).head()

0    1    2    3
0 -1.0 -1.0 -1.0  1.0
1 -1.0  1.0 -1.0  1.0
2  1.0 -1.0  1.0 -1.0
3 -1.0  1.0  1.0  1.0
4 -1.0  1.0  1.0 -1.0

In [64]:
df = pd.DataFrame(np.arange(5*4).reshape((5, 4)))
sampler = np.random.permutation(5)
sampler

array([4, 3, 1, 0, 2])

In [65]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [66]:
df.take(sampler)

0   1   2   3
4  16  17  18  19
3  12  13  14  15
1   4   5   6   7
0   0   1   2   3
2   8   9  10  11

In [67]:
df.sample(n=3)

0  1   2   3
2  8  9  10  11
0  0  1   2   3
1  4  5   6   7

In [69]:
choices = pd.Series([5, 7, -1, 6, 4])
draws = choices.sample(n=10, replace=True)
draws

1    7
3    6
2   -1
4    4
4    4
1    7
1    7
2   -1
2   -1
2   -1
dtype: int64

In [70]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'], 'data1': range(6)})
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [71]:
dummies = pd.get_dummies(df['key'], prefix='key')
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [74]:
mnames = ['movie_id', 'title', 'genres']
movies = pd.read_table('movielens/movies.dat', sep='::', header=None, names=mnames)
movies[:10]

C:\Users\B_Majda\Anaconda3\envs\pandas\lib\site-packages\ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  


movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [75]:
all_genres = []
for x in movies.genres:
    all_genres.extend(x.split('|'))
genres = pd.unique(all_genres)

In [76]:
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [77]:
zero_matrix = np.zeros((len(movies), len(genres)))
dummies = pd.DataFrame(zero_matrix, columns=genres)

In [78]:
gen= movies.genres[0]
gen.split('|')

['Animation', "Children's", 'Comedy']

In [80]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2], dtype=int64)

In [81]:
for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i, indices] = 1
    
movies_windic = movies.join(dummies.add_prefix('Genre_'))

In [82]:
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Adventure                                0
Genre_Fantasy                                  0
Genre_Romance                                  0
Genre_Drama                                    0
Genre_Action                                   0
Genre_Crime                                    0
Genre_Thriller                                 0
Genre_Horror                                   0
Genre_Sci-Fi                                   0
Genre_Documentary                              0
Genre_War                                      0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Film-Noir                                0
Genre_Western       

In [83]:
np.random.seed(42)
values = np.random.rand(10)
values

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

In [84]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           1           0           0           0
1           0           0           0           0           1
2           0           0           0           1           0
3           0           0           1           0           0
4           1           0           0           0           0
5           1           0           0           0           0
6           1           0           0           0           0
7           0           0           0           0           1
8           0           0           0           1           0
9           0           0           0           1           0