In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [3]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 29.6 ms


In [4]:
%time for _ in range(10): my_list2 = [ x * 2 for x in my_list]

Wall time: 975 ms


In [6]:
data = np.random.randn(2, 3)
data

array([[ 0.30918796,  0.04507417,  0.38200973],
       [-0.60091732,  1.21706819,  0.42542384]])

In [7]:
data * 10 

array([[ 3.09187963,  0.45074169,  3.82009733],
       [-6.00917321, 12.17068192,  4.25423843]])

In [8]:
data + data

array([[ 0.61837593,  0.09014834,  0.76401947],
       [-1.20183464,  2.43413638,  0.85084769]])

In [9]:
data.shape

(2, 3)

In [10]:
data.dtype

dtype('float64')

In [11]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [12]:
data2 = [[1, 2, 3, 4],[5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
arr2.ndim

2

In [14]:
arr2.shape

(2, 4)

In [15]:
arr1.dtype

dtype('float64')

In [16]:
arr2.dtype

dtype('int32')

In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [21]:
np.empty((2, 3, 2))

array([[[1.10909040e-311, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.10768180e-311, 3.54069004e-033]],

       [[1.93274621e-076, 3.21680150e-057],
        [5.85225940e+170, 1.39358531e+165],
        [2.95132250e+179, 1.33734816e+165]]])

In [22]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])